CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

.PHONY: clean all

fork: fork.c
	$(CC) $(CFLAGS) -o fork fork.c

ostep5c1: ostep5c1.c
	$(CC) $(CFLAGS) -o ostep5c1 ostep5c1.c

ostep5c2: ostep5c2.c
	$(CC) $(CFLAGS) -o ostep5c2 ostep5c2.c	

ostep5c3: ostep5c3.c
	$(CC) $(CFLAGS) -o ostep5c3 ostep5c3.c

ostep5c5: ostep5c5.c
	$(CC) $(CFLAGS) -o ostep5c5 ostep5c5.c

ostep5c6: ostep5c6.c
	$(CC) $(CFLAGS) -o ostep5c6 ostep5c6.c

