CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

.PHONY: clean all

mmap: mmap.c
	$(CC) $(CFLAGS) -o mmap mmap.c

compsys_malloc: compsys_malloc.c
	$(CC) $(CFLAGS) -o compsys_malloc compsys_malloc.c	
